services:
  postgres:
    image: postgres:16
    container_name: neo-postgres
    environment:
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: neo
      POSTGRES_DB: neo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: neo-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata: {}
  miniodata: {}
